# -*- jinx-languages: "es_ES"; -*-
#+title: Haitian 5
#+date: [2025-04-12 Sat 09:58]
#+filetags: :trabajo:castlight:
#+identifier: 20250412T095826
#+author: Ing. Javier Pacheco
#+startup: showall
* TODO Datos y especificaciones.
- Modelo :: H450
- Serie ::
- Peso máximo de platinas :: 6T

* Contraseñas
:PROPERTIES:
:VISIBILITY: folded
:END:
** lvl 12 :crypt:
-----BEGIN PGP MESSAGE-----

jA0ECQMKAaPc1QfCtCH/0lcBaMnh1FdEvTpL77hKh7HaBfyAFzkhhsyk8/UN9O8Z
9udhSLQ2accVd4E6uACOohNy2AN84R9o2eGaQdEuD6d3V6aXuM8YniZ9yytqm/RB
TyVuankmH+U=
=7J2y
-----END PGP MESSAGE-----

** lvl 8:
user: Servicer
pass: mtto450

** lvl 6:
user: Operator
pass: a123

** Driver: :crypt:
-----BEGIN PGP MESSAGE-----

jA0ECQMKO0KnhuhkGyD/0mwBc9BqSRhbBxlGSuA4yRvop5ZxQxU/9E825vkLizR1
m0KEUVLEdcNIb4NW4LCR3IOoGkFjyCZIJ7inMH0c3QxcJTG2zl8kWSz3VwxwxHAA
tVzcY3QqWzeUDqmt5AafamM9VLaolviuYjbT0sA=
=2aWT
-----END PGP MESSAGE-----

* Fallas Considerables.
** 4-Abril-2025
Maquina dejo de hacer movimientos, Se revisaron TODAS las válvulas del bloque de cierre, no se encontraron fallas aparentes. Por lo cual se decidió pedir soporte a =Haitian=.
Revisando con =Haitian China=, se dieron cuenta que habia unos parámetros movidos:
- Debug mode :: ON, (debe de estar OFF)
- Combined in Manual :: ON, (debe estar OFF)
- Use simplify mold open :: ON, (debe estar OFF)
- Use step movement :: OFF, (debe estar ON)

Al regresar estos valores a su estado normal, la maquina hizo movimientosnormales.
Cabe mencionar que esta maquina tenian acceso la mayoría de empleados al usuario de manager, por lo cual se cambiaron contraseñas, y se cargo un software con protección adicional, de manera que el acceso quedo restringido a como esta la Haitian 4, que para mover dichos parámetros se necesita un código QR que codifica =Haitian China= y que tiene vigencia de 10 minutos.

** 11-Abril-2025 2:30 pm
Revisando la maquina, Alejandro de Leon, nota que hay un ruido extraño en la maquina, a lo cual procedemos a revisar la bomba hidráulica, y notamos que en reposo la bomba estaba girando al revés. Esta maquina tiene tecnología =Echo Friendly=, lo cual significa que en reposo no debe estar girando la bomba. Revisamos el driver del motor, y notamos que tenia lectura de RPM's en valor negativo (por que estaba girando al revés).Pedimos soporte a Ángel del equipo de =Haitian=, y nos dieron instrucciones de revisar algunos parámetros del driver:

| Parametro | Valor antes | Valor Después | Comentarios                                                         |
|-----------+-------------+---------------+---------------------------------------------------------------------|
| Pr.09     |           0 |             5 | OK                                                                  |
| An.11     |        0.13 |             0 | Al arrancar cambio a -2.31 (al igual que el driver de la Haitian 4) |

Despues de modificar el =An.11=, el motor dejo de girar al revés, y quedo
trabajando correctamente.

*NOTE:* Despues volvio a fallar, se resolvio solo el problema.

**  3-Julio-2025
Reemplazo de empaques de Cilindro de cierre.

** El problema persiste.
Después de lo de los parámetros anteriores, el problema seguía presentándose, después nos dimos cuenta de que el parámetro *An.18* si se ponía a 0 entonces el driver volvía a su estado normal.

*** Septiembre 27.
El motor empezo a comportarse de la misma manera (girando en reversa en reposo), Intentamos poner el parametro *An.18* en 0, pero el problema persiste, Haitian esta en planta instalando las maquinas nuevas.

*NOTA:* El parametro =An.19= se puso en 3 en lugar de 0 corrigiendo la falla. Esto nos indica que la solucion a este detalle puede no ser ese parametro, ya que en las ocaciones pasadas el parametro =An.18= se encontraba con valor 3 y se movia a 0 para solucionar el detalle, ahora estaba en 1, se coloco en 0 sin solucion, despues se coloco 3 y respondio bien.
