# -*- jinx-languages: "es_ES"; -*-
#+title: Lógica de Programación
#+date: [2025-04-13 Sun 09:19]
#+filetags: :estudio:programacion:
#+identifier: 20250413T091934
#+author: Ing. Javier Pacheco
#+startup: showall
La lógica de programación, es la base de todo, de nada sirve aprender =X= lenguaje de programación si no sabes lo fundamental. En este caso la lógica de programación es importante, ya que esta es la que realmente te hace resolver problemas, el lenguaje de programación es la =herramienta= que te conducirá al resultado final.

Tiene sentido, un =loop, condicional, if, else if=, son lo mismo (al menos en lo que realizan o su propósito) pero en los lenguajes de programación lo único que los diferencia son su sintaxis.

La idea de aprender concepto es mas importante que aprender o memorizar codigo.

#+begin_quote
"Si aprendes los conceptos antes que el codigo, entenderas como intercambiarlos fácilmente."
#+end_quote

* DOING Como lleavarlo a la practica
Crear algún proyecto pero ir aumentando la dificultad.
** Pasos para crear un proyecto.

- Definir el objetivo ::  Definir que es lo que tu aplicacion sera util.
- Disenar la arquitectura :: Dibujar lo que la aplicacion realizara, apoyandote con diagramas de flujo, etc.
- Escribir codigo :: Aqui empezamos a escribir codigo usando las herramientas necesarias, incluyendo el lenguage de programacion, dependencias etc.
- Desfragmentar el proyecto :: una vez terminado el proyecto, ir cambiando cosas de este, ejemplo, si usas una base de datos en un archivi =.csv=, cambialo a una base de datos poco mas compleja como: =.db=

* Referencias
[[https://www.youtube.com/watch?v=ImOR0o-QHOQ&t=98s][Aprende conceptos antes que codigo - Fazt]]
