 -*- jinx-languages: "es_ES"; -*-
#+title: Python
#+date: [2025-04-11 Fri 21:04]
#+filetags: :meta:
#+identifier: 20250411T210418
#+author: Ing. Javier Pacheco
#+startup: content

Python es un lenguaje de alto nivel de programación interpretado cuya filosofía 
hace hincapié en la legibilidad de su código. Se trata de un lenguaje de programación
multiparadigma, ya que soporta parcialmente la orientación a objetos, programación
imperativa y, en menor medida, programación funcional. Es un lenguaje interpretado,
dinámico y multiplataforma.

Administrado por Python Software Foundation, posee una licencia de código abierto,
denominada Python Software Foundation License.​ Python se clasifica constantemente
como uno de los lenguajes de programación más populares.

Este lenguaje de programación es en el que me estaré especializando, bueno, este y
=common-lisp=.

#+BEGIN: denote-links :regexp "_estudio_python" :excluded-dirs-regexp nil :sort-by-component nil :reverse-sort nil :id-only nil :include-date nil
- [[file:20250410T203543==1=2--astral-uv__estudio_python.org][1=2  Astral UV]]
- [[file:20250410T203747==1=3--libros-de-python__estudio_python.org][1=3  Libros de python]]
- [[file:20250412T150343==1=1--aprendiendo-lo-basico__estudio_python.org][1=1  Aprendiendo lo basico]]
- [[file:20250412T153958==1=1=1--variables__estudio_python.org][1=1=1  Variables]]
#+END:

* Referencias.
1. [[https://www.python.org/][Python.org]]
2. [[https://www.w3schools.com/python][Python - w3school]]
3. [[mouredev.link/megapython][Curso de 33 horas de python - Pass: mega_course]]
   
