# -*- jinx-languages: "es_ES"; -*-
#+title: Funciones y Alcance
#+date: [2025-04-13 Sun 19:49]
#+filetags: :estudio:programacion:
#+identifier: 20250413T194946
#+author: Ing. Javier Pacheco
#+startup: showall
* DONE EJERCICIO: [5/5]
CLOSED: [2025-04-14 Mon 03:37]
- [X] Crea ejemplos de funciones básicas que representen las diferentes
  * posibilidades del lenguaje:
  * Sin parámetros ni retorno, con uno o varios parámetros, con retorno...
- [X] Comprueba si puedes crear funciones dentro de funciones.
- [X] Utiliza algún ejemplo de funciones ya creadas en el lenguaje.
- [X] Pon a prueba el concepto de variable LOCAL y GLOBAL.
- [X] Debes hacer print por consola del resultado de todos los ejemplos.
        (y tener en cuenta que cada lenguaje puede poseer más o menos posibilidades)

* TODO DIFICULTAD EXTRA (opcional): [/]
 * Crea una función que reciba dos parámetros de tipo cadena de texto y retorne un número.
- [ ] La función imprime todos los números del 1 al 100. Teniendo en cuenta que:
    - Si el número es múltiplo de 3, muestra la cadena de texto del primer parámetro.
    - Si el número es múltiplo de 5, muestra la cadena de texto del segundo parámetro.
    - Si el número es múltiplo de 3 y de 5, muestra las dos cadenas de texto concatenadas.
    - La función retorna el número de veces que se ha impreso el número en lugar de los textos.

 * Presta especial atención a la sintaxis que debes utilizar en cada uno de los casos.
 * Cada lenguaje sigue una convenciones que debes de respetar para que el código se entienda.

* Solución
:PROPERTIES:
:VISIBILITY: folded
:END:
#+begin_src python
# Con retorno
def greet(name):
    message = f"Hello, {name}!"
    return message
greet("Javier")

# Comprueba  funciones dentro de funciones
def greet(name):
    return f"Hello, {name}!"

def welcome_user(name):
    greeting = greet(name)
    return f"{greeting} Welcome to the system."

# Funcion built-in
lista = [1,5,8,3,14,4,8]
print(sorted(lista))

# Variable LOCAL
def sum_of_vars(x):
    local = 5
    return x + local

sum_of_vars(5)
print(local) # Aqui no funcionara,

# Variable GLOBAL
global = 10
def sum_of_vars(x):
    return x + global

sum_of_vars(5)
print(global) # Como es una variable GLOBAL, si funciona el print
#+end_src

* Solución Dificultad Extra.
:PROPERTIES:
:VISIBILITY: folded
:END:
#+begin_src python
def print_numbers(text_1, text_2) -> int:
    count = 0
    for number in range(1, 101):
        if number % 3 == 0 and number % 5 == 0:
            print(text_1 + text_2)
        elif number % 3 == 0:
            print(text_1)
        elif number % 5 == 0:
            print(text_2)
        else:
            print(number)
            count += 1
    return count

print(print_numbers("Fizz", "Buzz"))
#+end_src
* Mi solucion extra.
#+begin_src python
def fizz_buzz(text_1, text_2):
    count = 0
    for number in range(1,101):
        if number % 3 == 0 and number % 5 == 0:
            print(f"{text_1} {text_2}")
        elif number % 5 == 0:
            print(text_1)
        elif number % 3 == 0:
            print(text_2)
        else:
            print(number)
            count +=1

fizz_buzz("lia", "javier")
#+end_src

* Que aprendí:
En este modulo aprendi, a usar la logica para la creacion del tan famoso =FizzBuzz=, usando =if, elif, else=.
Mas que nada los conceptos fueron faciles, lo interesante fue entender el ejercicio extra y poder darte cuenta
que era el famoso fizzbuzz de toda la vida.
