# -*- jinx-languages: "es_ES"; -*-
#+title: Como plantar una piña
#+date: [2025-04-06 Sun 16:01]
#+filetags: :jardineria:proyecto:
#+identifier: 20250406T160108
#+author: Ing. Javier Pacheco
#+startup: content

1. Corta la corona de la piña
Toma una tabla de cocina y recorta la corona de la piña con cuidado de no quitarle las hojas y dañarla. ¡Ojo!, ten en cuenta que la corona será la raíz que ayudará a crecer.

2. Deja limpio el tronco de las hojas
Con la corona lista, donde posiblemente aún queden restos de pulpa, deberás retirar la fruta restante y las hojas que estén más cerca de la base. Una vez lo tengas todo listo, deja reposar la corona durante aproximadamente una semana y al revés, para que sus heridas se cierren.

3. llena un recipiente con agua
Prepara un recipiente con agua en el que dejarás la piña para que germine. Te recomendamos usar un recipiente de vidrio que pese, para evitar que se vuelque.

El agua únicamente debe mojar el tronco sin llegar a tocar las hojas, para evitar que se vayan pudriendo. Truco: si la piña es pequeña, o has tenido que retirar muchas hojas y la corona no es muy grande, te recomendamos utilizar un tarro de vidrio de yogur, porque tiene la boca estrecha. Además de ser práctico, ¡puede servirte como elemento decorativo!

4. Coloca el recipiente en una zona soleada
Si quieres que la piña conviva con el resto de tus plantas para jardín, sitúa el recipiente cerca de un lugar con mucha luz, pero alejado de la influencia directa si el sol es muy intenso donde vives. Te recomendamos mantener tu recipiente en un sitio con temperatura estable y que no baje nunca de los 18 °C.

5. Cambia el agua cada 48 o 72 horas
Tras varias semanas, deberías empezar a ver que van apareciendo las primeras raíces blancas en la base del tallo. Desde este momento, te recomendamos que vayas cambiando el agua cada 48 o 72 horas.
6. Prepara la maceta con tierra
Una vez que las raíces estén bien desarrolladas, prepara una maceta con un sustrato ligero y con buen drenaje. Te recomendamos que uses fibra de coco, humus de lombriz o turba.

7. Riega y cubre la maceta
Desde este punto, riega muy bien la piña plantada y con un spray de agua pulveriza las hojas. ¡Ojo!, no dejes que el sustrato se seque por completo, especialmente si vives en un clima seco.
