# -*- jinx-languages: "es_MX"; -*-; -*-
#+title: Procedimientos
#+date: [2025-04-12 Sat 21:43]
#+filetags: :trabajo:castlight:
#+identifier: 20250412T214322
#+author: Ing. Javier Pacheco
#+startup: showall

* Inyección.
Las maquinas Haitian trabajan con un calculo de presión para el =Fast= y el =Boost=, por lo cual por lo regular siempre manejan ambos la misma presión:
- 350 :: 100 bar.
- 450 :: 100 bar.
- 850 :: 150 bar.

Con estos valores de presiones, se tiene que hacer un calculo el cual es el siguiente: 
- presión de trabajo faster = presión real * 1.20
- presión de trabajo booster = presión real * 1.25

* Respaldo 
** Requerimientos.
- USB Formateada.
- Nivel de acceso de Manager/Engineer.
 
** Procedimiento.
1. Product.
2. System.
3. Backup/Restore.

*NOTAS IMPORTANTES*:
- Antes de hacer un respaldo, /Haitian/ recomienda siempre formatear la memoria.
- Cuando se haga un respaldo, asegurarse de que las casillas de *SRAM* y *EPROM* estén deshabilitadas, para no sobrescribir estos puntos.

** Como esa conformado el backup.
Suponiendo que la memoria sea: E:/
#+begin_example
E:/img
  |
  | log
#+end_example
