# -*- jinx-languages: "es_MX"; -*-
#+title: Método C.R.I.S.P.E.
#+date: [2026-04-25 Sat 11:35]
#+filetags: :estudio:ia:
#+identifier: 20260425T113540
#+author: Ing. Javier Pacheco
#+startup: showall


* Introducción:
Que son los =Prompts=?, un =prompt= es la pregunta que le haces a la =Inteligencia artificial= de tal manera que empiezas a generar una conversación, el truco esta en que dependiendo el =prompt= que hagas o como formules la pregunta o la solicitud, es la manera en la que la =inteligencia artificial= te contestara, porque ella no te conoce, no puede asumir lo que estas requiriendo, aunque eso si lo piensas es lo mismo si empiezas a hablar con una persona desconocida, eventualmente conocerá tus gustos, las respuestas que esperas, de echo es así como funcionan las inteligencias artificiales, mientras mas información tengan de =entrada= mejor sera la =salida=.

* Metodo C.R.I.S.P.E.
- C :: Context; Contexto; Que es lo que pretendes lograr, Cual es tu situacion, cual es tu =background=, y hacia quien va dirigido el contenido, o lo que deseas generar.
- R :: Role; El rol; Decirle a la =AI= el como quieres que te explique o redacte las cosas. ej: "actúa como una persona de xx edad, con experiencia de 10 años en programación".
- I :: Instruction; Instrucción; Esto es el que y como y cualquier requerimiento especifico y meta final, que es lo que tratas de lograr.
- S :: Specification; Especificaciones; Ser especifico en como quieres el formato; si con viñetas, tipo de párrafos, cantidad de hojas, tono de voz, ejemplos de introducciones, etc.
- P :: Performance; Especifica tu estándar de calidad, explícale como esperas ver el resultado, los métricos que esperas ver, y/o cosas que quieras evitar decir para cierta audiencia.
- E :: Example; Muéstrale un ejemplo de como debería de verse, comparte algún ejemplo de alguien mas para que lo compare.
 
* Ejemplo de Prompt:
#+begin_example
Hello World!
#+end_example

* Referencias:
[[https://www.youtube.com/watch?v=0FRgzoP5Mw4][Master AI Prompting: The CRISPE Method Explained!]]
