# -*- jinx-languages: "es_MX"; -*-
#+title: List Comprehensions
#+date: [2026-05-10 Sun 13:02]
#+filetags: :estudio:python:
#+identifier: 20260510T130229
#+author: Ing. Javier Pacheco
#+startup: showall


* Definición y conceptos:
La comprensión de listas, del inglés list comprehensions, es una funcionalidad que nos permite crear listas avanzadas en una misma línea de código. Esto se ve mucho mejor en la práctica, así que a lo largo de esta lección vamos a trabajar distintos ejemplos.

* Uso general de listas:
En el siguiente ejemplo, elevaremos al cuadrado una lista de números como lo haríamos de forma convencional:

#+begin_src python :results output :exports both
nums_squared = []
nums = [1, 2, 3, 4, 5]
for n in nums:
    square = n**2
    nums_squared.append(square)

print(nums_squared)
#+end_src
En el ejemplo vemos que funciona pero, son 5 lineas de código que por su puesto se puede mejorar.

* List comprehentions:
** Estructura:
La lista la podemos visualizar de la siguiente manera:

- [  {parte 1} {parte 2} {parte 3}  ]

- Parte 1 :: La operación final, en nuestro ejemplo sera la =elevación al cuadrado=.
- Parte 2 :: La operación que usaremos, en nuestro ejemplo es el =for=.
- Parte 3 :: Lista original

Para entender mejor la estructura como =tip=, es bueno empezar a escribir la =lista comprensiva= al revés, osea: =parte 3 -> parte 2 -> parte 1=

#+BEGIN_SRC python :results output :exports both
nums = [1, 2, 3, 4, 5]
num_squared = [n**2 for n in nums]

print(num_squared)
#+END_SRC

** Ejemplo 2
En el siguiente ejemplo =Capitalizaremos= la primer letra de cada palabra en la lista de =tv_shows=.

#+BEGIN_SRC python :results output :exports both
tv_shows = [ "friends", "PARKS AND RECREATION", "the Office", "30 rock", "modern FAMILY"]
tv_shows_cap = []
for show in tv_shows:
    show_cap = show.title()
    tv_shows_cap.append(show_cap)
print (tv_shows_cap)
#+END_SRC

Ahora lo haremos con la lista comprensiva:

#+BEGIN_SRC python :results output :exports both
tv_shows = [ "friends", "PARKS AND RECREATION", "the Office", "30 rock", "modern FAMILY"]
tv_shows_cap = [show.title() for show in tv_shows] 
print(tv_shows_cap)
#+END_SRC
