#+TITLE: Examen - PLC Basico
#+AUTHOR: Ing. Javier Pacheco
#+DATE: 22-Marzo-2025
#+LaTeX_CLASS: exam
#+OPTIONS: toc:nil date:nil title:nil num:nil author: t

#+BEGIN_EXPORT latex
\pagestyle{headandfoot}

\firstpageheader{
\textbf{Examen - Nombre del examen: PLC Basico (\numpoints\ puntos)} \\
\vspace*{0.5cm} % Espacio en blanco (ajusta el valor según sea necesario)
\textbf{Nombre:} \underline{\hspace{4in}}
}{}{}

\runningheader{Nombre del examen: PLC Basico}{}{Pagina \thepage\ de \numpages}
\runningheadrule

\firstpagefooter{}{}{}
\runningfooter{}{}{}
#+END_EXPORT

# Instrucciones de la primer seccion.
#+begin_export latex
\begin{center}
\fbox{\fbox{%
\begin{minipage}{\dimexpr\textwidth-8\fboxsep-8\fboxrule\relax} % Ajusta el ancho
\centering
\textbf{Contesta la pregunta con pluma de color azul, no subrayes, rellena el recuadro.}
\end{minipage}%
}}
\end{center}
#+end_export

# Preguntas de Opcion multiple.
#+begin_export latex
\begin{questions}
\question[5]
\textbf{En un PLC, elmodulo de entrada se utiliza para:}

\begin{choices}
\choice Enviar senales a actuadores.
\choice Procesar la logica del programa.
\choice Recibir senales de sensores.
\choice Almacenar datos en memoria.
\end{choices}

\question[15]
\textbf{Cual es el valor decimal del siguiente numero en binario: 0011}

\begin{choices}
\choice 5
\choice 6
\choice 2
\choice 3
\end{choices}

\end{questions}
#+end_export

# Preguntas de razonamiento
