# -*- jinx-languages: "es_ES"; -*-
#+TITLE: Examen - Curso Básico de PLC
#+AUTHOR: Ing. Javier Pacheco
#+DATE: May 2025
#+LaTeX_CLASS: exam
#+OPTIONS: toc:nil date:nil title:nil num:nil author: t

#+BEGIN_EXPORT latex
\pagestyle{headandfoot}

\firstpageheader{
\textbf{Curso Basico de PLC (\numpoints\ puntos)} \\
\vspace*{0.5cm}
\textbf{Nombre:} \underline{\hspace{4in}}
}{}{}

\runningheader{Curso Basico de PLC}{}{Pagina \thepage\ de \numpages}
\runningheadrule

\firstpagefooter{}{}{}
\runningfooter{}{}{}
#+END_EXPORT

* Primera Seccion.
#+BEGIN_EXPORT latex
\begin{center}
\fbox{\fbox{%
\begin{minipage}{\dimexpr\textwidth-8\fboxsep-8\fboxrule\relax} % Ajusta el ancho
\centering
\textbf{Contesta las siguientes preguntas con pluma color azul, subraya la respuesta que concideres correcta.}
\end{minipage}%
}}
\end{center}
#+END_EXPORT

#+LATEX: \begin{questions}
#+LATEX: \question[3]
Cual de las siguientes marcas son fabricantes de PLC:
- [ ] AllenBradley
- [ ] Fanuc.
- [ ] Siemes.
- [ ] Todas las anteriores.

#+LATEX: \question[3]
Esta opcion carga la logica del PLC al ordenador para su evaluación
- [ ] Save
- [ ] Download
- [ ] upload
- [ ] Close

#+LATEX: \question[3]
Cuál de los siguientes lenguajes de programación NO es comúnmente utilizado en PLCs
- [ ] Ladder Diagram (LD)
- [ ] Structured Text (ST)
- [ ] Python
- [ ] Function Block Diagram (FBD)

#+LATEX: \question[3]
Qué tipo de señal es más común en las entradas digitales de un PLC
- [ ] Señal analógica de 0-10V
- [ ] Señal digital de 24V DC
- [ ] Señal de audio
- [ ] Señal de red Ethernet

#+LATEX: \question[5]
En un PLC, qué hace un relé interno (marcador)
- [ ] Controla directamente un motor
- [ ] Almacena un valor lógico (verdadero/falso)
- [ ] Convierte señales analógicas a digitales
- [ ] Gestiona la comunicación de red

#+LATEX: \question[3]
Cual de los siguientes es un ejemplo de una salida digital en un PLC
- [ ] Encender una lámpara
- [ ] Medir la temperatura
- [ ] Controlar la velocidad de un motor
- [ ] Leer un sensor de proximidad
     
* Segunda Seccion.
#+begin_export latex
\begin{center}
\fbox{\fbox{%
\begin{minipage}{\dimexpr\textwidth-8\fboxsep-8\fboxrule\relax} % Ajusta el ancho
\centering
\textbf{La siguiente seccion es un para de razonamientos logicos, tendras que explicarlos. Usa lapiz.}
\end{minipage}%
}}
\end{center}
#+end_export

#+LATEX: \question[15]
Dibuja el paro arranque de un motor en logica *LADDER*.
#+LATEX: \vspace{\stretch{1}}

#+LATEX: \question[15]
Programa un timer que este periodicamente contando 30 segundos.
#+LATEX: \vspace{\stretch{1}}

#+LATEX: \end{questions}
